/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IO;
import Pessoas.*;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import tiadvanced.*;
/**
 *
 * @author Aluno
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        String[] novo = new String[2];
        novo[0] = "Teste";
        novo[1] = "Teste2";
        jList1.setListData(novo);
        telaLogin.pack();
        telaCliente.pack();
        telaFuncionario.pack();
        telaOrcamentos.pack();
        telaCadastro.pack();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaCadastro = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        telefoneCadastrar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        enderecoCadastrar = new javax.swing.JTextField();
        usuarioCadastrar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailCadastrar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        passwordCadastrar = new javax.swing.JPasswordField();
        tipoCadastrar = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        nomeCadastrar = new javax.swing.JTextField();
        telaLogin = new javax.swing.JDialog();
        usuarioLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passwordLogin = new javax.swing.JPasswordField();
        botaoLogin = new javax.swing.JButton();
        botaoCadastro = new javax.swing.JButton();
        telaFuncionario = new javax.swing.JDialog();
        valorServico = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AtribuirValor = new javax.swing.JButton();
        cadastroServicoFunc = new javax.swing.JButton();
        verificarPedidosFunc = new javax.swing.JButton();
        nomeServicoFunc = new javax.swing.JTextField();
        verificarPedidosFunc1 = new javax.swing.JButton();
        deslogarFunc = new javax.swing.JButton();
        servicosValidos = new javax.swing.JComboBox<>();
        telaCliente = new javax.swing.JDialog();
        verificaPedido2 = new javax.swing.JButton();
        cadastroServico2 = new javax.swing.JButton();
        nomeServicoCli = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        realizarPedido = new javax.swing.JButton();
        deslogarCli = new javax.swing.JButton();
        telaOrcamentos = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        promocao = new javax.swing.JTextField();
        promover = new javax.swing.JButton();
        cadastrarADM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        deslogarADM = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        validar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        nomeServicoADM = new javax.swing.JTextField();
        cadastroServicoADM = new javax.swing.JButton();

        jLabel19.setText("Nome:");

        telefoneCadastrar.setText("Telefone");

        jLabel20.setText("Endereço:");

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        enderecoCadastrar.setText("Endereço");

        usuarioCadastrar.setText("Usuario");

        jLabel21.setText("Telefone:");

        jLabel2.setText("User:");

        emailCadastrar.setText("Email");

        jLabel22.setText("Password:");

        jLabel23.setText("Email:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("CADASTRO");

        passwordCadastrar.setText("password");

        tipoCadastrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("Tipo:");

        nomeCadastrar.setText("Nome");

        javax.swing.GroupLayout telaCadastroLayout = new javax.swing.GroupLayout(telaCadastro.getContentPane());
        telaCadastro.getContentPane().setLayout(telaCadastroLayout);
        telaCadastroLayout.setHorizontalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel24))
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel25))
                            .addGroup(telaCadastroLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(tipoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enderecoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefoneCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomeCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(usuarioCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(BotaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        telaCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailCadastrar, enderecoCadastrar, nomeCadastrar, passwordCadastrar, telefoneCadastrar, tipoCadastrar, usuarioCadastrar});

        telaCadastroLayout.setVerticalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addComponent(usuarioCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(passwordCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCadastrar)
                .addGap(20, 20, 20))
        );

        telaCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailCadastrar, enderecoCadastrar, nomeCadastrar, passwordCadastrar, telefoneCadastrar, tipoCadastrar, usuarioCadastrar});

        telaLogin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FecharTela(evt);
            }
        });

        usuarioLogin.setText("Usuario");

        jLabel5.setText("User:");

        jLabel6.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("LOGIN");

        passwordLogin.setText("jPasswordField1");

        botaoLogin.setText("Login");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        botaoCadastro.setText("Cadastro");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaLoginLayout = new javax.swing.GroupLayout(telaLogin.getContentPane());
        telaLogin.getContentPane().setLayout(telaLoginLayout);
        telaLoginLayout.setHorizontalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(passwordLogin)))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(botaoLogin)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCadastro))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel8)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        telaLoginLayout.setVerticalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLogin)
                    .addComponent(botaoCadastro))
                .addContainerGap())
        );

        telaFuncionario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FecharTela(evt);
            }
        });

        valorServico.setText("Valor do Serviço");

        jLabel15.setText("Serviço:");

        jLabel16.setText("Serviços Válidos:");

        jLabel17.setText("R$:");

        AtribuirValor.setText("Atribuir Valor a Serviço");
        AtribuirValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtribuirValorActionPerformed(evt);
            }
        });

        cadastroServicoFunc.setText("Cadastrar Serviço");
        cadastroServicoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroServicoFuncActionPerformed(evt);
            }
        });

        verificarPedidosFunc.setText("Verificar Pedidos");

        nomeServicoFunc.setText("Nome do Serviço");

        verificarPedidosFunc1.setText("Verificar Orçamentos");

        deslogarFunc.setText("Deslogar");
        deslogarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deslogarFuncActionPerformed(evt);
            }
        });

        servicosValidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout telaFuncionarioLayout = new javax.swing.GroupLayout(telaFuncionario.getContentPane());
        telaFuncionario.getContentPane().setLayout(telaFuncionarioLayout);
        telaFuncionarioLayout.setHorizontalGroup(
            telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFuncionarioLayout.createSequentialGroup()
                .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaFuncionarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9)
                        .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(telaFuncionarioLayout.createSequentialGroup()
                                .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(telaFuncionarioLayout.createSequentialGroup()
                                        .addComponent(nomeServicoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFuncionarioLayout.createSequentialGroup()
                                        .addComponent(cadastroServicoFunc)
                                        .addGap(132, 132, 132)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(servicosValidos, 0, 162, Short.MAX_VALUE))
                            .addGroup(telaFuncionarioLayout.createSequentialGroup()
                                .addComponent(verificarPedidosFunc1)
                                .addGap(18, 18, 18)
                                .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(telaFuncionarioLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AtribuirValor)))))
                    .addGroup(telaFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deslogarFunc)
                        .addGap(121, 121, 121)
                        .addComponent(verificarPedidosFunc)))
                .addContainerGap())
        );
        telaFuncionarioLayout.setVerticalGroup(
            telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFuncionarioLayout.createSequentialGroup()
                .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaFuncionarioLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(nomeServicoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(servicosValidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastroServicoFunc)
                            .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(valorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGap(10, 10, 10)
                        .addComponent(verificarPedidosFunc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFuncionarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AtribuirValor)
                        .addGap(18, 18, 18)))
                .addGroup(telaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verificarPedidosFunc)
                    .addComponent(deslogarFunc))
                .addContainerGap())
        );

        telaCliente.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FecharTela(evt);
            }
        });

        verificaPedido2.setText("Verificar Pedidos Realizados");
        verificaPedido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaPedido2ActionPerformed(evt);
            }
        });

        cadastroServico2.setText("Cadastrar Serviço");
        cadastroServico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroServico2ActionPerformed(evt);
            }
        });

        nomeServicoCli.setText("Nome do Serviço");
        nomeServicoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeServicoCliActionPerformed(evt);
            }
        });

        jLabel18.setText("Serviço:");

        realizarPedido.setText("Realizar Pedido");

        deslogarCli.setText("Deslogar");
        deslogarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deslogarCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaClienteLayout = new javax.swing.GroupLayout(telaCliente.getContentPane());
        telaCliente.getContentPane().setLayout(telaClienteLayout);
        telaClienteLayout.setHorizontalGroup(
            telaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaClienteLayout.createSequentialGroup()
                .addGroup(telaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(telaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cadastroServico2)
                            .addComponent(realizarPedido)
                            .addComponent(verificaPedido2)
                            .addComponent(deslogarCli)))
                    .addGroup(telaClienteLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(2, 2, 2)
                        .addComponent(nomeServicoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaClienteLayout.setVerticalGroup(
            telaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(telaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeServicoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroServico2)
                .addGap(27, 27, 27)
                .addComponent(realizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verificaPedido2)
                .addGap(18, 18, 18)
                .addComponent(deslogarCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jButton19.setText("Alterar Orcamento");

        jButton20.setText("Deletar Orcamento");

        javax.swing.GroupLayout telaOrcamentosLayout = new javax.swing.GroupLayout(telaOrcamentos.getContentPane());
        telaOrcamentos.getContentPane().setLayout(telaOrcamentosLayout);
        telaOrcamentosLayout.setHorizontalGroup(
            telaOrcamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaOrcamentosLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(telaOrcamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton20)
                    .addComponent(jButton19)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        telaOrcamentosLayout.setVerticalGroup(
            telaOrcamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaOrcamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("TelaADM"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FecharTela(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("OPERACÕES");

        jLabel10.setText("Criar ADM:");

        promocao.setText("Usuario");

        promover.setText("Promover");
        promover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoverActionPerformed(evt);
            }
        });

        cadastrarADM.setText("Cadastrar novo ADM");
        cadastrarADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarADMActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);
        jList1.getAccessibleContext().setAccessibleName("");
        jList1.getAccessibleContext().setAccessibleDescription("");

        deslogarADM.setText("Deslogar");
        deslogarADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deslogarADMActionPerformed(evt);
            }
        });

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        validar.setText("Validar");
        validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarActionPerformed(evt);
            }
        });

        deletar.setText("Deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        jLabel26.setText("Serviço:");

        nomeServicoADM.setText("Nome do Serviço");

        cadastroServicoADM.setText("Cadastrar Serviço");
        cadastroServicoADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroServicoADMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(promover)
                                        .addGap(110, 110, 110)
                                        .addComponent(cadastroServicoADM))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(promocao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(84, 84, 84)
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nomeServicoADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(cadastrarADM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deslogarADM)
                        .addGap(99, 99, 99)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alterar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deletar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alterar, deletar, validar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(nomeServicoADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(validar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(promover)
                            .addComponent(cadastroServicoADM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarADM)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletar)
                    .addComponent(deslogarADM))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cadastrarADM, promocao, promover});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        if(system.Cadastro(nomeCadastrar.getText(), enderecoCadastrar.getText(), telefoneCadastrar.getText(), emailCadastrar.getText(), usuarioCadastrar.getText(), new String(passwordCadastrar.getPassword()),tipoCadastrar.getSelectedItem().toString())){
            nomeCadastrar.setText("Nome");
            telefoneCadastrar.setText("Telefone");
            enderecoCadastrar.setText("Endereço");
            emailCadastrar.setText("Email");
            usuarioCadastrar.setText("Usuario");
            passwordCadastrar.setText("password");
            telaCadastro.dispose();
        } 
        
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        
        String senha = new String(passwordLogin.getPassword());
        
        if(system.Login(usuarioLogin.getText(), senha)){            
            usuarioLogin.setText("Usuario");
            passwordLogin.setText("Password");
            telaLogin.dispose();
            switch(system.getNivelAcesso()){
                case 2:
                    setVisible(true);                    
                    break;
                case 1:
                    telaFuncionario.setVisible(true);
                    break;
                case 0:
                default:
                    telaCliente.setVisible(true);
                    break;
            }            
        }
        else{            
            usuarioLogin.setText("Usuario");
            passwordLogin.setText("Password");
        }
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        tipoCadastrar.removeAllItems();
        tipoCadastrar.addItem(Funcionario.ID);
        tipoCadastrar.addItem(Clientes.ID);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void cadastroServicoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroServicoFuncActionPerformed
        system.cadastrarServico(nomeServicoFunc.getText());
    }//GEN-LAST:event_cadastroServicoFuncActionPerformed

    private void verificaPedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaPedido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verificaPedido2ActionPerformed

    private void cadastroServico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroServico2ActionPerformed
        system.cadastrarServico(nomeServicoCli.getText());
    }//GEN-LAST:event_cadastroServico2ActionPerformed

    private void FecharTela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FecharTela
        system.getData().save();
        System.exit(0);
    }//GEN-LAST:event_FecharTela

    private void cadastrarADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarADMActionPerformed
        tipoCadastrar.removeAllItems();
        tipoCadastrar.addItem(Funcionario.ID);
        tipoCadastrar.addItem(Clientes.ID);
        tipoCadastrar.addItem(Administrador.ID);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_cadastrarADMActionPerformed

    private void deslogarADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deslogarADMActionPerformed
        system.deslogar();
        dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_deslogarADMActionPerformed

    private void deslogarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deslogarFuncActionPerformed
        system.deslogar();
        telaFuncionario.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_deslogarFuncActionPerformed

    private void deslogarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deslogarCliActionPerformed
        system.deslogar();
        telaCliente.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_deslogarCliActionPerformed

    private void AtribuirValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtribuirValorActionPerformed
        system.precificarServico(servicosValidos.getSelectedItem().toString(), Double.parseDouble(valorServico.getText()));
    }//GEN-LAST:event_AtribuirValorActionPerformed

    private void nomeServicoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeServicoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeServicoCliActionPerformed

    private void promoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoverActionPerformed
        system.promover(promocao.getText());
    }//GEN-LAST:event_promoverActionPerformed

    private void validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarActionPerformed
        system.validarServico(jList1.getSelectedValuesList());
    }//GEN-LAST:event_validarActionPerformed

    private void cadastroServicoADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroServicoADMActionPerformed
        system.cadastrarServico(nomeServicoADM.getText());
    }//GEN-LAST:event_cadastroServicoADMActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        system.DeletarServico(jList1.getSelectedValuesList());
    }//GEN-LAST:event_deletarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        system.modificarServico(jList1.getSelectedValuesList());
    }//GEN-LAST:event_alterarActionPerformed
    
    
    public void inicio(){
        telaLogin.setVisible(true);
    }
    
    public void setSystem(Sistema system) {
        this.system = system;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtribuirValor;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton alterar;
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton cadastrarADM;
    private javax.swing.JButton cadastroServico2;
    private javax.swing.JButton cadastroServicoADM;
    private javax.swing.JButton cadastroServicoFunc;
    private javax.swing.JButton deletar;
    private javax.swing.JButton deslogarADM;
    private javax.swing.JButton deslogarCli;
    private javax.swing.JButton deslogarFunc;
    private javax.swing.JTextField emailCadastrar;
    private javax.swing.JTextField enderecoCadastrar;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nomeCadastrar;
    private javax.swing.JTextField nomeServicoADM;
    private javax.swing.JTextField nomeServicoCli;
    private javax.swing.JTextField nomeServicoFunc;
    private javax.swing.JPasswordField passwordCadastrar;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JTextField promocao;
    private javax.swing.JButton promover;
    private javax.swing.JButton realizarPedido;
    private javax.swing.JComboBox<String> servicosValidos;
    private javax.swing.JDialog telaCadastro;
    private javax.swing.JDialog telaCliente;
    private javax.swing.JDialog telaFuncionario;
    private javax.swing.JDialog telaLogin;
    private javax.swing.JDialog telaOrcamentos;
    private javax.swing.JTextField telefoneCadastrar;
    private javax.swing.JComboBox<String> tipoCadastrar;
    private javax.swing.JTextField usuarioCadastrar;
    private javax.swing.JTextField usuarioLogin;
    private javax.swing.JButton validar;
    private javax.swing.JTextField valorServico;
    private javax.swing.JButton verificaPedido2;
    private javax.swing.JButton verificarPedidosFunc;
    private javax.swing.JButton verificarPedidosFunc1;
    // End of variables declaration//GEN-END:variables
    private Sistema system;  
}
